/// <reference lib="deno.ns" />
/**
 * SolidJS 2.0 is being used, and this file is a modification of
 * the boilerplate generated by the SolidJS project init tool.
 *
 * @see https://www.solidjs.com/blog/solid-2-0-rc-the-big-reveal
 *
 * Dependencies **ONLY** used in this file are imported directly.
 * They are development-time only: the aim is to keep the import map
 * in `deno.json` for runtime dependencies only.
 * This means versions must be updated manually; I find the tradeoff
 * worthwhile from a cognitive perspective.
 *
 * @module
 */

// deno-lint-ignore-file no-import-prefix
import { defineConfig } from "npm:vite@^8.3.0";
import { default as solidPlugin } from "npm:@solidjs/vite-plugin@^3.0.0-next.44";
import { fileRoutes } from "npm:filesystem-routing@0.3.0/vite";
import "npm:@solidjs/diagnostics@^2.0.0-rc.9";

const privateDir = new URL("./private/", import.meta.url);

export default defineConfig({
  clearScreen: false,
  plugins: [
    solidPlugin({
      start: true,
      extensions: [".jsx", ".tsx"],
      diagnostics: true,
    }),
    fileRoutes(),
  ],
  server: {
    https: {
      key: Deno.readTextFileSync(new URL("devkey.pem", privateDir)),
      cert: Deno.readTextFileSync(new URL("devcert.pem", privateDir)),
    },
  },
});
